Больше подробностей (часть 2)
htmlacademy-react/2397293-six-cities-13 pull request #6
Opened 2023-08-03 16:35 UTC by AndreyDev22

---
:mortar_board: [Больше подробностей (часть 2)](https://up.htmlacademy.ru/react/13/user/2397293/tasks/8)

2023-08-04 06:52 UTC, baileys-li requested changes

2023-08-04 06:52 UTC, baileys-li commented on src/components/card/card.tsx
>  				<a href="#">
А сделай ссылки на страницу

2023-08-04 06:55 UTC, AndreyDev22 commented on src/components/card/card.tsx
>  				<a href="#">
так там eslint ругается, все равно сделать?

2023-08-05 13:07 UTC, baileys-li requested changes
Подставь другие данные на страницу оффера и пройдись по проекту и оставь ссылки на другие страницы

2023-08-05 13:07 UTC, baileys-li commented on src/components/reviews-item/reviews-item.tsx
> +					{reviewData.date}
Нужно форматирование даты

2023-08-08 17:22 UTC, baileys-li commented on src/components/reviews-item/reviews-item.tsx
> +						src="img/avatar-max.jpg"
Аватарка тоже приходит из пропсов

2023-08-08 17:22 UTC, merged